CREATE OR REPLACE VIEW VI_KIERUNEK AS
SELECT DISTINCT KIERUNEK_ID KIERUNEK_ID , DATA_OD, DATA_DO  FROM OKRES_ST;

CREATE OR REPLACE VIEW VI_SEMESTR_PRZEDMIOT AS
SELECT * FROM SEMESTR_PRZEDMIOT LEFT OUTER JOIN PRZEDMIOT  ON PRZEDMIOT.ID = SEMESTR_PRZEDMIOT.PRZEDMIOT_ID;

CREATE OR REPLACE VIEW VI_SEMESTR_IL_WYK AS
SELECT DISTINCT SEMESTR_ID , SUM(IL_WYK) SUMA_WYK FROM VI_SEMESTR_PRZEDMIOT GROUP BY SEMESTR_ID;

CREATE OR REPLACE VIEW VI_KIERUNEK_GRUPY AS
SELECT ROK, MC ,KIERUNEK.ID  KIERUNEK_ID , COUNT(STUDENT_ID) IL_STUD, MAX_GRUPA ,
CASE WHEN TRUNCATE(COUNT(STUDENT_ID) / MAX_GRUPA , 0)  * MAX_GRUPA < COUNT(STUDENT_ID) THEN   TRUNCATE(COUNT(STUDENT_ID) / MAX_GRUPA , 0) +1
ELSE TRUNCATE(COUNT(STUDENT_ID) / MAX_GRUPA , 0)
END  ILE_GRUP
FROM OKRES_SYM JOIN    OKRES_ST ON ROK_MC BETWEEN EXTRACT(YEAR_MONTH FROM  DATA_OD) AND    EXTRACT(YEAR_MONTH FROM DATA_DO)
JOIN    KIERUNEK ON OKRES_ST.KIERUNEK_ID = KIERUNEK.ID
GROUP BY ROK, MC ,KIERUNEK.ID;

/*PRZYCHODY W ROKU I MIESIĄCU*/
CREATE OR REPLACE VIEW VI_PRZYCHOD AS
SELECT ROK*MC*KIERUNEK.ID ID,ROK, MC ,KIERUNEK.ID KIERUNEK , COUNT(STUDENT_ID) IL_STUD, COUNT(STUDENT_ID) * (CZESNE / 6) PRZYCHOD,  COUNT(STUDENT_ID) *  3.25 KOSZT_NA_ST
FROM OKRES_SYM JOIN    OKRES_ST ON ROK_MC BETWEEN EXTRACT(YEAR_MONTH FROM  DATA_OD) AND    EXTRACT(YEAR_MONTH FROM DATA_DO)
JOIN    KIERUNEK ON OKRES_ST.KIERUNEK_ID = KIERUNEK.ID
GROUP BY ROK, MC ,KIERUNEK.ID;


/*KOSZTY W ROKU I MIESIĄCU*/
CREATE OR REPLACE VIEW VI_KOSZT AS
SELECT DISTINCT OKRES_SYM.ROK AS ROK,
OKRES_SYM.MC AS MC,
VI_KIERUNEK.KIERUNEK_ID AS KIERUNEK_ID,
SEMESTR.ID AS ID,ROUND((((VI_SEMESTR_IL_WYK.SUMA_WYK * VI_KIERUNEK_GRUPY.ILE_GRUP) / 6) * 15),2) AS KOSZT_WYKLADW
FROM ((((OKRES_SYM JOIN VI_KIERUNEK ON((OKRES_SYM.ROK_MC BETWEEN EXTRACT(YEAR_MONTH 
FROM VI_KIERUNEK.DATA_OD) AND EXTRACT(YEAR_MONTH FROM VI_KIERUNEK.DATA_DO)))) 
JOIN SEMESTR ON((SEMESTR.KIERUNEK_ID = VI_KIERUNEK.KIERUNEK_ID))) 
JOIN VI_SEMESTR_IL_WYK ON((SEMESTR.ID = VI_SEMESTR_IL_WYK.SEMESTR_ID)))
JOIN VI_KIERUNEK_GRUPY ON(((VI_KIERUNEK_GRUPY.ROK = OKRES_SYM.ROK)
AND (VI_KIERUNEK_GRUPY.MC = OKRES_SYM.MC) AND (VI_KIERUNEK_GRUPY.KIERUNEK_ID = VI_KIERUNEK.KIERUNEK_ID)))) 
WHERE (OKRES_SYM.ROK_MC BETWEEN EXTRACT(YEAR_MONTH 
FROM (VI_KIERUNEK.DATA_OD + INTERVAL ((SEMESTR.NUMER - 1) * 6) MONTH)) AND EXTRACT(YEAR_MONTH 
FROM (VI_KIERUNEK.DATA_OD + INTERVAL (SEMESTR.NUMER * 6) MONTH)))
GROUP BY OKRES_SYM.ROK,OKRES_SYM.MC,VI_KIERUNEK.KIERUNEK_ID,SEMESTR.ID ORDER BY 1,2,3,4;

/*KOSZTY W ROKU I MIESIĄCU ZSUMOWANE*/
CREATE OR REPLACE VIEW VI_KOSZT_TEST AS
SELECT ROK, MC, KIERUNEK_ID, SUM(KOSZT_WYKLADW) KOSZT_WYKLADW FROM VI_KOSZT
GROUP BY ROK, MC, KIERUNEK_ID;

CREATE OR REPLACE VIEW VI_PRZYCHOD_KOSZT AS
SELECT distinct (A.ROK*A.MC)+C.ID as ID,
A.ROK, A.MC,
CASE  A.MC
WHEN 1 THEN  'Styczeń'
WHEN 2 THEN  'Luty'
WHEN 3 THEN  'Marzec'
WHEN 4 THEN  'Kwiecień'
WHEN 5 THEN  'Maj'
WHEN 6 THEN  'Czerwiec'
WHEN 7 THEN  'Lipiec'
WHEN 8 THEN  'Sierpień'
WHEN 9 THEN  'Wrzesień'
WHEN 10 THEN  'Październik'
WHEN 11 THEN  'Listopad'
ELSE 'Grudzień'
END AS MIESIAC , C.NAZWA KIERUNEK,  ROUND(B.PRZYCHOD,2) PRZYCHOD, ROUND(A.KOSZT_WYKLADW,2) KOSZT, ROUND((B.PRZYCHOD - A.KOSZT_WYKLADW),2) DOCHOD, B.KOSZT_NA_ST, B.IL_STUD
FROM VI_KOSZT_TEST A JOIN VI_PRZYCHOD B ON B.ROK= A.ROK AND B.MC = A.MC AND A.KIERUNEK_ID =  B.KIERUNEK
JOIN KIERUNEK C ON C.ID = A.KIERUNEK_ID ;
