insert into przedmiot (id, nazwa) values (1, 'vitae');
insert into przedmiot (id, nazwa) values (2, 'sit amet');
insert into przedmiot (id, nazwa) values (3, 'proin leo');
insert into przedmiot (id, nazwa) values (4, 'dolor sit');
insert into przedmiot (id, nazwa) values (5, 'felis');
insert into przedmiot (id, nazwa) values (6, 'nisi venenatis');
insert into przedmiot (id, nazwa) values (7, 'vestibulum sed');
insert into przedmiot (id, nazwa) values (8, 'ultrices libero non');
insert into przedmiot (id, nazwa) values (9, 'aenean sit amet');
insert into przedmiot (id, nazwa) values (10, 'diam');
insert into przedmiot (id, nazwa) values (11, 'morbi quis');
insert into przedmiot (id, nazwa) values (12, 'tellus semper');
insert into przedmiot (id, nazwa) values (13, 'nisi venenatis tristique');
insert into przedmiot (id, nazwa) values (14, 'lobortis sapien sapien');
insert into przedmiot (id, nazwa) values (15, 'amet sem');
insert into przedmiot (id, nazwa) values (16, 'ornare imperdiet');
insert into przedmiot (id, nazwa) values (17, 'augue vestibulum rutrum');
insert into przedmiot (id, nazwa) values (18, 'volutpat eleifend donec');
insert into przedmiot (id, nazwa) values (19, 'euismod');
insert into przedmiot (id, nazwa) values (20, 'ante');
insert into przedmiot (id, nazwa) values (21, 'convallis');
insert into przedmiot (id, nazwa) values (22, 'sit amet eleifend');
insert into przedmiot (id, nazwa) values (23, 'at nunc');
insert into przedmiot (id, nazwa) values (24, 'quis orci');
insert into przedmiot (id, nazwa) values (25, 'pede justo');
insert into przedmiot (id, nazwa) values (26, 'et magnis');
insert into przedmiot (id, nazwa) values (27, 'dui nec');
insert into przedmiot (id, nazwa) values (28, 'orci');
insert into przedmiot (id, nazwa) values (29, 'curae nulla dapibus');
insert into przedmiot (id, nazwa) values (30, 'sed accumsan felis');
insert into przedmiot (id, nazwa) values (31, 'sem duis aliquam');
insert into przedmiot (id, nazwa) values (32, 'bibendum felis');
insert into przedmiot (id, nazwa) values (33, 'nulla');
insert into przedmiot (id, nazwa) values (34, 'nibh');
insert into przedmiot (id, nazwa) values (35, 'sit');
insert into przedmiot (id, nazwa) values (36, 'felis ut');
insert into przedmiot (id, nazwa) values (37, 'mauris lacinia sapien');
insert into przedmiot (id, nazwa) values (38, 'ante nulla justo');
insert into przedmiot (id, nazwa) values (39, 'luctus et');
insert into przedmiot (id, nazwa) values (40, 'non lectus');
insert into przedmiot (id, nazwa) values (41, 'eu sapien');
insert into przedmiot (id, nazwa) values (42, 'aenean');
insert into przedmiot (id, nazwa) values (43, 'curae duis faucibus');
insert into przedmiot (id, nazwa) values (44, 'sem');
insert into przedmiot (id, nazwa) values (45, 'phasellus in');
insert into przedmiot (id, nazwa) values (46, 'suscipit a');
insert into przedmiot (id, nazwa) values (47, 'eu est congue');
insert into przedmiot (id, nazwa) values (48, 'habitasse platea');
insert into przedmiot (id, nazwa) values (49, 'elementum eu interdum');
insert into przedmiot (id, nazwa) values (50, 'odio');
