function usosweb(){var O='bootstrap',P='begin',Q='gwt.codesvr.usosweb=',R='gwt.codesvr=',S='usosweb',T='startup',U='DUMMY',V=0,W=1,X='iframe',Y='javascript:""',Z='position:absolute; width:0; height:0; border:none; left: -1000px;',$=' top: -1000px;',_='CSS1Compat',ab='<!doctype html>',bb='',cb='<html><head><\/head><body><\/body><\/html>',db='undefined',eb='DOMContentLoaded',fb=50,gb='Chrome',hb='eval("',ib='");',jb='script',kb='javascript',lb='moduleStartup',mb='moduleRequested',nb='Failed to load ',ob='head',pb='meta',qb='name',rb='usosweb::',sb='::',tb='gwt:property',ub='content',vb='=',wb='gwt:onPropertyErrorFn',xb='Bad handler "',yb='" for "gwt:onPropertyErrorFn"',zb='gwt:onLoadErrorFn',Ab='" for "gwt:onLoadErrorFn"',Bb='#',Cb='?',Db='/',Eb='img',Fb='clear.cache.gif',Gb='baseUrl',Hb='usosweb.nocache.js',Ib='base',Jb='//',Kb='user.agent.os',Lb='macintosh',Mb='mac os x',Nb='mac',Ob='linux',Pb='windows',Qb='win32',Rb='unknown',Sb=2,Tb=3,Ub='selectingPermutation',Vb='usosweb.devmode.js',Wb='DC1E33DFB4E99574BECE08B02F71EF47',Xb=':1',Yb=':2',Zb=':3',$b=':',_b=10,ac='.cache.js',bc='loadExternalRefs',cc='end',dc='http:',ec='file:',fc='_gwt_dummy_',gc='__gwtDevModeHook:usosweb',hc='Ignoring non-whitelisted Dev Mode URL: ',ic=':moduleBase';var o=window;var p=document;r(O,P);function q(){var a=o.location.search;return a.indexOf(Q)!=-1||a.indexOf(R)!=-1}
function r(a,b){if(o.__gwtStatsEvent){o.__gwtStatsEvent({moduleName:S,sessionId:o.__gwtStatsSessionId,subSystem:T,evtGroup:a,millis:(new Date).getTime(),type:b})}}
usosweb.__sendStats=r;usosweb.__moduleName=S;usosweb.__errFn=null;usosweb.__moduleBase=U;usosweb.__softPermutationId=V;usosweb.__computePropValue=null;usosweb.__getPropMap=null;usosweb.__installRunAsyncCode=function(){};usosweb.__gwtStartLoadingFragment=function(){return null};usosweb.__gwt_isKnownPropertyValue=function(){return false};usosweb.__gwt_getMetaProperty=function(){return null};var s=null;var t=o.__gwt_activeModules=o.__gwt_activeModules||{};t[S]={moduleName:S};usosweb.__moduleStartupDone=function(e){var f=t[S].bindings;t[S].bindings=function(){var a=f?f():{};var b=e[usosweb.__softPermutationId];for(var c=V;c<b.length;c++){var d=b[c];a[d[V]]=d[W]}return a}};var u;function v(){w();return u}
function w(){if(u){return}var a=p.createElement(X);a.src=Y;a.id=S;a.style.cssText=Z+$;a.tabIndex=-1;p.body.appendChild(a);u=a.contentDocument;if(!u){u=a.contentWindow.document}u.open();var b=document.compatMode==_?ab:bb;u.write(b+cb);u.close()}
function A(k){function l(a){function b(){if(typeof p.readyState==db){return typeof p.body!=db&&p.body!=null}return /loaded|complete/.test(p.readyState)}
var c=b();if(c){a();return}function d(){if(!c){c=true;a();if(p.removeEventListener){p.removeEventListener(eb,d,false)}if(e){clearInterval(e)}}}
if(p.addEventListener){p.addEventListener(eb,d,false)}var e=setInterval(function(){if(b()){d()}},fb)}
function m(c){function d(a,b){a.removeChild(b)}
var e=v();var f=e.body;var g;if(navigator.userAgent.indexOf(gb)>-1&&window.JSON){var h=e.createDocumentFragment();h.appendChild(e.createTextNode(hb));for(var i=V;i<c.length;i++){var j=window.JSON.stringify(c[i]);h.appendChild(e.createTextNode(j.substring(W,j.length-W)))}h.appendChild(e.createTextNode(ib));g=e.createElement(jb);g.language=kb;g.appendChild(h);f.appendChild(g);d(f,g)}else{for(var i=V;i<c.length;i++){g=e.createElement(jb);g.language=kb;g.text=c[i];f.appendChild(g);d(f,g)}}}
usosweb.onScriptDownloaded=function(a){l(function(){m(a)})};r(lb,mb);var n=p.createElement(jb);n.src=k;if(usosweb.__errFn){n.onerror=function(){usosweb.__errFn(S,new Error(nb+code))}}p.getElementsByTagName(ob)[V].appendChild(n)}
usosweb.__startLoadingFragment=function(a){return D(a)};usosweb.__installRunAsyncCode=function(a){var b=v();var c=b.body;var d=b.createElement(jb);d.language=kb;d.text=a;c.appendChild(d);c.removeChild(d)};function B(){var c={};var d;var e;var f=p.getElementsByTagName(pb);for(var g=V,h=f.length;g<h;++g){var i=f[g],j=i.getAttribute(qb),k;if(j){j=j.replace(rb,bb);if(j.indexOf(sb)>=V){continue}if(j==tb){k=i.getAttribute(ub);if(k){var l,m=k.indexOf(vb);if(m>=V){j=k.substring(V,m);l=k.substring(m+W)}else{j=k;l=bb}c[j]=l}}else if(j==wb){k=i.getAttribute(ub);if(k){try{d=eval(k)}catch(a){alert(xb+k+yb)}}}else if(j==zb){k=i.getAttribute(ub);if(k){try{e=eval(k)}catch(a){alert(xb+k+Ab)}}}}}__gwt_getMetaProperty=function(a){var b=c[a];return b==null?null:b};s=d;usosweb.__errFn=e}
function C(){function e(a){var b=a.lastIndexOf(Bb);if(b==-1){b=a.length}var c=a.indexOf(Cb);if(c==-1){c=a.length}var d=a.lastIndexOf(Db,Math.min(c,b));return d>=V?a.substring(V,d+W):bb}
function f(a){if(a.match(/^\w+:\/\//)){}else{var b=p.createElement(Eb);b.src=a+Fb;a=e(b.src)}return a}
function g(){var a=__gwt_getMetaProperty(Gb);if(a!=null){return a}return bb}
function h(){var a=p.getElementsByTagName(jb);for(var b=V;b<a.length;++b){if(a[b].src.indexOf(Hb)!=-1){return e(a[b].src)}}return bb}
function i(){var a=p.getElementsByTagName(Ib);if(a.length>V){return a[a.length-W].href}return bb}
function j(){var a=p.location;return a.href==a.protocol+Jb+a.host+a.pathname+a.search+a.hash}
var k=g();if(k==bb){k=h()}if(k==bb){k=i()}if(k==bb&&j()){k=e(p.location.href)}k=f(k);return k}
function D(a){if(a.match(/^\//)){return a}if(a.match(/^[a-zA-Z]+:\/\//)){return a}return usosweb.__moduleBase+a}
function F(){var f=[];var g=V;function h(a,b){var c=f;for(var d=V,e=a.length-W;d<e;++d){c=c[a[d]]||(c[a[d]]=[])}c[a[e]]=b}
var i=[];var j=[];function k(a){var b=j[a](),c=i[a];if(b in c){return b}var d=[];for(var e in c){d[c[e]]=e}if(s){s(a,d,b)}throw null}
j[Kb]=function(){var a=o.navigator.userAgent.toLowerCase();if(a.indexOf(Lb)!=-1||a.indexOf(Mb)!=-1){return Nb}if(a.indexOf(Ob)!=-1){return Ob}if(a.indexOf(Pb)!=-1||a.indexOf(Qb)!=-1){return Pb}return Rb};i[Kb]={linux:V,mac:W,unknown:Sb,windows:Tb};__gwt_isKnownPropertyValue=function(a,b){return b in i[a]};usosweb.__getPropMap=function(){var a={};for(var b in i){if(i.hasOwnProperty(b)){a[b]=k(b)}}return a};usosweb.__computePropValue=k;o.__gwt_activeModules[S].bindings=usosweb.__getPropMap;r(O,Ub);if(q()){return D(Vb)}var l;try{h([Ob],Wb);h([Nb],Wb+Xb);h([Rb],Wb+Yb);h([Pb],Wb+Zb);l=f[k(Kb)];var m=l.indexOf($b);if(m!=-1){g=parseInt(l.substring(m+W),_b);l=l.substring(V,m)}}catch(a){}usosweb.__softPermutationId=g;return D(l+ac)}
function G(){if(!o.__gwt_stylesLoaded){o.__gwt_stylesLoaded={}}r(bc,P);r(bc,cc)}
B();usosweb.__moduleBase=C();t[S].moduleBase=usosweb.__moduleBase;var H=F();if(o){var I=!!(o.location.protocol==dc||o.location.protocol==ec);o.__gwt_activeModules[S].canRedirect=I;function J(){var b=fc;try{o.sessionStorage.setItem(b,b);o.sessionStorage.removeItem(b);return true}catch(a){return false}}
if(I&&J()){var K=gc;var L=o.sessionStorage[K];if(!/^http:\/\/(localhost|127\.0\.0\.1)(:\d+)?\/.*$/.test(L)){if(L&&(window.console&&console.log)){console.log(hc+L)}L=bb}if(L&&!o[K]){o[K]=true;o[K+ic]=C();var M=p.createElement(jb);M.src=L;var N=p.getElementsByTagName(ob)[V];N.insertBefore(M,N.firstElementChild||N.children[V]);return false}}}G();r(O,cc);A(H);return true}
usosweb.succeeded=usosweb();